### PR TITLE
Created Nemanja package with a WelcomeSharks.txt file

### PR DESCRIPTION
**Pull request by Nemanja9513**
Hi Fouad, hope everything is well. Please review and let me know if anything needs changing.
Thanks!

### CODE REVIEW

**Comment by fouad077** [comment]
This is looking good. I left a few comments

**Comment by fouad077** [comment]
Hi Nemanja let me know if you need anything else thank you.

**Comment by Nemanja9513** [comment]
Hi Fouad, I believe that you have to approve the review in order to merge the pull request.
Thanks in advance!

**Review by Mars13O — APPROVED** [review]
Looks good

**Pull request merged**
